{
	"openapi": "3.0.0",
	"info": {
		"description": "",
		"version": "1.0.0",
		"title": "qore-console"
	},
	"servers": [
		{
			"url": "http://localhost:8012/backend"
		}
	],
	"tags": [
		{
			"name": "account",
			"description": "後台帳號"
		},
		{
			"name": "qore/account",
			"description": "qore帳號"
		},
		{
			"name": "qore/auth",
			"description": "API權限"
		},
		{
			"name": "qore/vendors",
			"description": "商家"
		},
		{
			"name": "security",
			"description": "資安相關"
		}
	],
	"paths": {
		"/qore/account": {
			"get": {
				"tags": [
					"qore/account"
				],
				"summary": "[6001]qore+帳號_取得(/qore/account)",
				"parameters": [
					{
						"type": "string",
						"name": "page",
						"in": "query",
						"default": "1",
						"description": "頁數(從1開始)"
					},
					{
						"type": "string",
						"name": "pageSize",
						"in": "query",
						"default": "10",
						"description": "頁寬度"
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"code": {
											"type": "integer",
											"description": "錯誤代碼",
											"default": 0
										},
										"data": {
											"type": "object",
											"properties": {
												"list": {
													"type": "array",
													"items": {
														"type": "object",
														"properties": {
															"id": {
																"type": "integer",
																"description": "",
																"default": 1
															},
															"account": {
																"type": "string",
																"description": "",
																"default": "justkitchen"
															},
															"password": {
																"type": "string",
																"description": "",
																"default": "1qaz2wsx"
															},
															"pickup_no_prefix": {
																"type": "string",
																"description": "取餐號開頭(2~3碼)",
																"default": "HK"
															},
															"enable": {
																"type": "string",
																"description": "1: true, 0: false",
																"default": "1"
															},
															"auth": {
																"type": "string",
																"description": "權限等級",
																"default": "1"
															},
															"vendor_id": {
																"type": "string",
																"description": "商家ID",
																"default": "JUSTKITCHEN"
															},
															"token": {
																"type": "string",
																"description": "登入crm用的token",
																"default": "f6aea4337b414bc1ab5c29e36c3ec5b9"
															},
															"token_date": {
																"type": "string",
																"description": "登入crm用的",
																"default": "2099-12-31T09:35:05.000Z"
															},
															"created_at": {
																"type": "string",
																"description": "建立時間",
																"default": "2021-03-12T10:22:52.000Z"
															},
															"updated_at": {
																"type": "string",
																"description": "更新時間",
																"default": "2021-03-12T10:22:52.000Z"
															}
														},
														"required": [
															"id",
															"account",
															"password",
															"pickup_no_prefix",
															"enable",
															"auth",
															"vendor_id",
															"token",
															"token_date",
															"created_at",
															"updated_at"
														]
													}
												},
												"rowsNum": {
													"type": "integer",
													"description": "資料總筆數",
													"default": 37
												}
											},
											"required": [
												"list",
												"rowsNum"
											]
										},
										"msg": {
											"type": "string",
											"description": "訊息字串",
											"default": "ok"
										}
									},
									"required": [
										"code",
										"data",
										"msg"
									]
								}
							}
						}
					}
				},
				"security": [
					{
						"Token": [
							
						]
					}
				]
			},
			"post": {
				"tags": [
					"qore/account"
				],
				"summary": "[6002]qore+帳號_新增(/qore/account)",
				"parameters": [
					
				],
				"security": [
					{
						"Token": [
							
						]
					}
				],
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"account": {
										"type": "string",
										"description": "",
										"default": "useThomas"
									},
									"password": {
										"type": "string",
										"description": "",
										"default": "test123456"
									},
									"vendor_id": {
										"type": "string",
										"description": "",
										"default": "JUSTKITCHEN"
									},
									"auth": {
										"type": "string",
										"description": "",
										"default": "1"
									},
									"token_date": {
										"type": "string",
										"description": "",
										"default": "2023-02-15T03:59:25.932Z"
									},
									"pickup_no_prefix": {
										"type": "string",
										"description": "",
										"default": "HK"
									},
									"enable": {
										"type": "boolean",
										"description": "",
										"default": true
									}
								},
								"required": [
									"account",
									"password",
									"vendor_id",
									"auth",
									"token_date",
									"pickup_no_prefix",
									"enable"
								]
							},
							"examples": {
								"useThomas": {
									"value": {
										"account": "useThomas",
										"password": "test123456",
										"vendor_id": "JUSTKITCHEN",
										"auth": "1",
										"token_date": "2023-02-15T03:59:25.932Z",
										"pickup_no_prefix": "HK",
										"enable": true
									}
								}
							}
						}
					}
				}
			}
		},
		"/account/login": {
			"post": {
				"tags": [
					"account"
				],
				"summary": "[1001]登入(/account/login)",
				"parameters": [
					
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"code": {
											"type": "integer",
											"description": "",
											"default": 0
										},
										"data": {
											"type": "object",
											"properties": {
												"token": {
													"type": "string",
													"description": "",
													"default": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjc2MDA2NTY4LCJleHAiOjE2NzYwOTI5Njh9.bVKXtZcStmLR6KtR0OGn6Zc7kkG8e2cdE851Y_OFCxc"
												},
												"role": {
													"type": "string",
													"description": "",
													"default": "admin"
												},
												"account": {
													"type": "object",
													"properties": {
														"id": {
															"type": "integer",
															"description": "",
															"default": 2
														}
													},
													"required": [
														
													]
												}
											},
											"required": [
												"account"
											]
										},
										"msg": {
											"type": "string",
											"description": "",
											"default": "ok"
										}
									},
									"required": [
										"data"
									]
								}
							}
						}
					}
				},
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"account": {
										"type": "string",
										"description": "帳號",
										"default": "thomaswang@reas.com.tw"
									},
									"password": {
										"type": "string",
										"description": "密碼",
										"default": "123456"
									}
								},
								"required": [
									"account",
									"password"
								]
							}
						}
					}
				}
			}
		},
		"/account/profile": {
			"get": {
				"tags": [
					"account"
				],
				"summary": "[1003]個人後台帳號資料_取得(/account/profile)",
				"security": [
					{
						"Token": [
							
						]
					}
				],
				"parameters": [
					
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"code": {
											"type": "integer",
											"description": ""
										},
										"data": {
											"type": "object",
											"properties": {
												"id": {
													"type": "integer",
													"description": "",
													"default": 2
												},
												"account": {
													"type": "string",
													"description": "",
													"default": "thomaswang@reas.com.tw"
												},
												"email": {
													"type": "string",
													"description": "",
													"default": "thomaswang@reas.com.tw"
												},
												"name": {
													"type": "string",
													"description": "",
													"default": "Thomas"
												},
												"enabled": {
													"type": "boolean",
													"description": "",
													"default": true
												},
												"last_login_at": {
													"type": "string",
													"description": "",
													"default": "2023-02-02T06:51:16.000Z"
												},
												"activated": {
													"type": "boolean",
													"description": "",
													"default": false
												},
												"created_at": {
													"type": "string",
													"description": "",
													"default": "2023-02-02T06:51:16.000Z"
												},
												"updated_at": {
													"type": "string",
													"description": "",
													"default": "2023-02-02T06:51:16.000Z"
												},
												"role_id": {
													"type": "integer",
													"description": "",
													"default": 1
												},
												"role_key": {
													"type": "string",
													"description": "",
													"default": "admin"
												}
											},
											"required": [
												
											]
										},
										"msg": {
											"type": "string",
											"description": "",
											"default": "ok"
										}
									},
									"required": [
										
									]
								}
							}
						}
					}
				}
			},
			"put": {
				"tags": [
					"account"
				],
				"summary": "[1004]個人後台帳號資料_修改(/account/profile)",
				"parameters": [
					
				],
				"responses": {
					
				},
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"name": {
										"type": "string",
										"description": ""
									},
									"password": {
										"type": "string",
										"description": ""
									}
								},
								"required": [
									
								]
							}
						}
					}
				},
				"security": [
					{
						"Token": [
							
						]
					}
				]
			}
		},
		"/account": {
			"post": {
				"tags": [
					"account"
				],
				"summary": "[1011]帳號資料_新增",
				"parameters": [
					
				],
				"responses": {
					
				},
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"account": {
										"type": "string",
										"description": ""
									},
									"password": {
										"type": "string",
										"description": ""
									},
									"name": {
										"type": "string",
										"description": ""
									}
								},
								"required": [
									"account",
									"password",
									"name"
								]
							}
						}
					}
				},
				"security": [
					{
						"Token": [
							
						]
					}
				]
			},
			"get": {
				"tags": [
					"account"
				],
				"summary": "[1012]帳號資料_取得",
				"parameters": [
					{
						"type": "string",
						"name": "id",
						"in": "query",
						"default": "2",
						"description": "account_id"
					}
				],
				"responses": {
					
				},
				"security": [
					{
						"Token": [
							
						]
					}
				]
			},
			"patch": {
				"tags": [
					"account"
				],
				"summary": "[1013]帳號資料_修改",
				"parameters": [
					
				],
				"responses": {
					
				},
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"id": {
										"type": "integer",
										"description": "account_id",
										"default": 2
									},
									"name": {
										"type": "string",
										"description": "帳號名稱",
										"default": "Thomas"
									},
									"password": {
										"type": "string",
										"description": "密碼",
										"default": "123456"
									},
									"email": {
										"type": "string",
										"description": "",
										"default": "aaaa@bbb.ccc"
									},
									"enabled": {
										"type": "boolean",
										"description": "帳號可用",
										"default": true
									},
									"activated": {
										"type": "boolean",
										"description": "帳號已激活",
										"default": true
									}
								},
								"required": [
									"id"
								]
							}
						}
					}
				},
				"security": [
					{
						"Token": [
							
						]
					}
				]
			},
			"delete": {
				"tags": [
					"account"
				],
				"summary": "[1014]帳號資料_刪除",
				"parameters": [
					
				],
				"responses": {
					
				},
				"security": [
					{
						"Token": [
							
						]
					}
				]
			}
		},
		"/account/role": {
			"put": {
				"tags": [
					"account"
				],
				"summary": "[1015]帳號角色_更新",
				"parameters": [
					
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"code": {
											"type": "integer",
											"description": ""
										},
										"data": {
											"type": "object",
											"properties": {
												"result": {
													"type": "boolean",
													"description": ""
												}
											},
											"required": [
												
											]
										},
										"msg": {
											"type": "string",
											"description": ""
										}
									},
									"required": [
										
									]
								}
							}
						}
					}
				},
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"id": {
										"type": "integer",
										"description": ""
									},
									"role": {
										"type": "string",
										"description": ""
									}
								},
								"required": [
									"id",
									"role"
								]
							}
						}
					}
				},
				"security": [
					{
						"Token": [
							
						]
					}
				]
			}
		},
		"/qore/vendor": {
			"get": {
				"tags": [
					"qore/vendors"
				],
				"summary": "[6021]qore+商家_查詢(/qore/vendor)",
				"parameters": [
					{
						"type": "string",
						"name": "page",
						"in": "query",
						"default": "1",
						"description": ""
					},
					{
						"type": "string",
						"name": "pageSize",
						"in": "query",
						"default": "10",
						"description": ""
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"code": {
											"type": "integer",
											"description": "",
											"default": 0
										},
										"data": {
											"type": "object",
											"properties": {
												"list": {
													"type": "array",
													"items": {
														"type": "object",
														"properties": {
															"id": {
																"type": "integer",
																"description": "",
																"default": 1
															},
															"vendor_id": {
																"type": "string",
																"description": "",
																"default": "JUSTKITCHEN"
															},
															"crm_id": {
																"type": "string",
																"description": "",
																"default": "echoss"
															},
															"vendor_name": {
																"type": "string",
																"description": "",
																"default": "JUST KITCHEN 軒饌廚坊"
															},
															"vat_no": {
																"type": "string",
																"description": "",
																"default": "82899761"
															},
															"vendor_pic": {
																"type": "string",
																"description": "",
																"default": "FB_IMG_1607101132384.jpg"
															},
															"vendor_desc": {
																"type": "string",
																"description": "",
																"default": "Just Kitchen 虛擬廚房"
															},
															"vendor_web": {
																"type": "string",
																"description": "",
																"default": "https://www.justkitchen.com/"
															},
															"vendor_tel": {
																"type": "string",
																"description": "",
																"default": "02-2658-0808"
															},
															"vendor_email": {
																"type": "string",
																"description": "",
																"default": "info@justkitchen.com"
															},
															"vendor_addr": {
																"type": "string",
																"description": "",
																"default": "台北市內湖區陽光街 365 巷 39 號 1 樓"
															},
															"created_at": {
																"type": "string",
																"description": "",
																"default": "2020-12-26T05:20:00.000Z"
															},
															"updated_at": {
																"type": "string",
																"description": "",
																"default": "2022-08-04T17:56:20.000Z"
															}
														},
														"required": [
															
														]
													}
												},
												"rowsNum": {
													"type": "integer",
													"description": "",
													"default": 5
												}
											},
											"required": [
												
											]
										},
										"msg": {
											"type": "string",
											"description": "",
											"default": "ok"
										}
									},
									"required": [
										
									]
								}
							}
						}
					}
				},
				"security": [
					{
						"Token": [
							
						]
					}
				]
			}
		},
		"/qore/account/{id}": {
			"get": {
				"tags": [
					"qore/account"
				],
				"summary": "[6006]qore+帳號_查詢單筆(/qore/account/{id})",
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"code": {
											"type": "integer",
											"description": "",
											"default": 0
										},
										"data": {
											"type": "object",
											"properties": {
												"id": {
													"type": "integer",
													"description": "",
													"default": 52
												},
												"account": {
													"type": "string",
													"description": "",
													"default": "JudyUat"
												},
												"password": {
													"type": "string",
													"description": ""
												},
												"pickup_no_prefix": {
													"type": "string",
													"description": "",
													"default": "HK"
												},
												"enable": {
													"type": "boolean",
													"description": "",
													"default": true
												},
												"auth": {
													"type": "integer",
													"description": "",
													"default": "1"
												},
												"vendor_id": {
													"type": "string",
													"description": "",
													"default": "SHAKU"
												},
												"token": {
													"type": "string",
													"description": "",
													"default": "5e2b3c1ff56ca35e98bf5848bac065b5"
												},
												"token_date": {
													"type": "string",
													"description": "",
													"default": "2099-12-31T00:00:00.000Z"
												},
												"created_at": {
													"type": "string",
													"description": "",
													"default": "2023-01-11T14:59:35.000Z"
												},
												"updated_at": {
													"type": "string",
													"description": "",
													"default": "2023-02-09T12:00:02.000Z"
												}
											},
											"required": [
												
											]
										},
										"msg": {
											"type": "string",
											"description": "",
											"default": "ok"
										}
									},
									"required": [
										
									]
								},
								"examples": {
									"useThomas": {
										"value": {
											"code": 0,
											"data": {
												"id": 56,
												"account": "useThomas",
												"password": null,
												"pickup_no_prefix": "HK",
												"enable": true,
												"auth": 1,
												"vendor_id": "SHAKU",
												"token": "0b13e7041c2202f8bdb6bfad4f0532b7",
												"token_date": "2023-02-15T00:00:00.000Z",
												"created_at": "2023-02-15T12:12:44.000Z",
												"updated_at": "2023-02-15T17:58:56.000Z"
											},
											"msg": "ok"
										}
									}
								}
							}
						}
					}
				},
				"security": [
					{
						"Token": [
							
						]
					}
				],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "account_id",
						"required": false,
						"schema": {
							"type": "string"
						},
						"default": "56"
					}
				]
			},
			"patch": {
				"tags": [
					"qore/account"
				],
				"summary": "[6005]qore+帳號_修改(/qore/account)",
				"parameters": [
					
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"code": {
											"type": "integer",
											"description": "",
											"default": 0
										},
										"data": {
											"type": "object",
											"properties": {
												"apiRes": {
													"type": "object",
													"properties": {
														"status": {
															"type": "boolean",
															"description": "",
															"default": true
														},
														"result": {
															"type": "string",
															"description": "",
															"default": "修改成功"
														},
														"message": {
															"type": "object",
															"properties": {
																"tokenAuth": {
																	"type": "string",
																	"description": "",
																	"default": "呼叫成功"
																}
															},
															"required": [
																
															]
														}
													},
													"required": [
														
													]
												}
											},
											"required": [
												
											]
										},
										"msg": {
											"type": "string",
											"description": "",
											"default": "ok"
										}
									},
									"required": [
										
									]
								},
								"examples": {
									"stateChange": {
										"value": {
											"code": 0,
											"data": {
												"apiRes": {
													"status": true,
													"result": "修改成功",
													"message": {
														"tokenAuth": "呼叫成功，由 shakuDev 呼叫"
													}
												}
											},
											"msg": "ok"
										}
									}
								}
							}
						}
					}
				},
				"security": [
					{
						"Token": [
							
						]
					}
				],
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"enable": {
										"type": "boolean",
										"description": "",
										"default": true
									}
								},
								"required": [
									"enable"
								]
							},
							"examples": {
								"stateEnable": {
									"value": {
										"enable": true
									}
								}
							}
						}
					}
				}
			},
			"put": {
				"tags": [
					"qore/account"
				],
				"summary": "[6007]qore+帳號_更新(/qore/account/{id})",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "account_id",
						"required": true,
						"schema": {
							"type": "string"
						},
						"default": "56"
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"code": {
											"type": "integer",
											"description": "",
											"default": 0
										},
										"data": {
											"type": "object",
											"properties": {
												"apiRes": {
													"type": "object",
													"properties": {
														"success": {
															"type": "boolean",
															"description": "",
															"default": true
														},
														"message": {
															"type": "string",
															"description": "",
															"default": ""
														},
														"response": {
															"type": "object",
															"description": "",
															"properties": {
																
															}
														}
													},
													"required": [
														
													]
												}
											},
											"required": [
												
											]
										},
										"msg": {
											"type": "string",
											"description": "",
											"default": "ok"
										}
									},
									"required": [
										
									]
								}
							}
						}
					}
				},
				"security": [
					{
						"Token": [
							
						]
					}
				],
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"password": {
										"type": "string",
										"description": "",
										"default": "123456"
									},
									"pickup_no_prefix": {
										"type": "string",
										"description": "",
										"default": "HK"
									},
									"enable": {
										"type": "boolean",
										"description": "",
										"default": false
									},
									"auth": {
										"type": "integer",
										"description": "",
										"default": 1
									},
									"vendor_id": {
										"type": "string",
										"description": "",
										"default": "SHAKU"
									},
									"token_date": {
										"type": "string",
										"description": "",
										"default": "2023-03-30T16:00:00.000Z"
									}
								},
								"required": [
									"password",
									"pickup_no_prefix",
									"enable",
									"auth",
									"vendor_id",
									"token_date"
								]
							}
						}
					}
				}
			}
		},
		"/qore/auth": {
			"get": {
				"tags": [
					"qore/auth"
				],
				"summary": "[6041]Qore+API權限_查詢(/qore/auth)",
				"parameters": [
					{
						"type": "string",
						"name": "page",
						"in": "query",
						"default": "1",
						"description": "頁數"
					},
					{
						"type": "string",
						"name": "size",
						"in": "query",
						"default": "10",
						"description": "查詢量"
					}
				],
				"security": [
					{
						"Token": [
							
						]
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"code": {
											"type": "integer",
											"description": "",
											"default": 0
										},
										"data": {
											"type": "object",
											"properties": {
												"list": {
													"type": "array",
													"items": {
														"type": "object",
														"properties": {
															"id": {
																"type": "integer",
																"description": "",
																"default": 1
															},
															"url": {
																"type": "string",
																"description": "",
																"default": "/api/order"
															},
															"method": {
																"type": "string",
																"description": "",
																"default": "POST"
															},
															"auth": {
																"type": "integer",
																"description": "",
																"default": 2
															},
															"enable": {
																"type": "boolean",
																"description": "",
																"default": true
															},
															"created_at": {
																"type": "string",
																"description": "",
																"default": "2021-04-23T17:32:02.000Z"
															},
															"updated_at": {
																"type": "string",
																"description": "",
																"default": "2021-04-23T17:32:02.000Z"
															}
														},
														"required": [
															
														]
													}
												},
												"rowsNum": {
													"type": "integer",
													"description": "",
													"default": 101
												}
											},
											"required": [
												
											]
										},
										"msg": {
											"type": "string",
											"description": "",
											"default": "ok"
										}
									},
									"required": [
										
									]
								}
							}
						}
					}
				}
			},
			"post": {
				"tags": [
					"qore/auth"
				],
				"summary": "[6042]Qore+API權限_新增(/qore/auth)",
				"parameters": [
					
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"code": {
											"type": "integer",
											"description": "",
											"default": 0
										},
										"data": {
											"type": "object",
											"properties": {
												"result": {
													"type": "boolean",
													"description": "",
													"default": true
												},
												"apiRes": {
													"type": "object",
													"properties": {
														"success": {
															"type": "boolean",
															"description": "",
															"default": true
														},
														"message": {
															"type": "integer",
															"description": "",
															"default": 0
														},
														"response": {
															"type": "object",
															"properties": {
																
															},
															"required": [
																
															]
														}
													},
													"required": [
														
													]
												}
											},
											"required": [
												
											]
										},
										"msg": {
											"type": "string",
											"description": "",
											"default": "ok"
										}
									},
									"required": [
										
									]
								}
							}
						}
					}
				},
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"apiRoute": {
										"type": "string",
										"description": "",
										"default": "/test/thomas/008"
									},
									"methodType": {
										"type": "string",
										"description": "",
										"default": "put"
									},
									"auth": {
										"type": "integer",
										"description": "",
										"default": 1
									},
									"memo": {
										"type": "string",
										"description": "",
										"default": "/test/thomas/008"
									}
								},
								"required": [
									"apiRoute",
									"methodType",
									"auth",
									"memo"
								]
							},
							"examples": {
								"/test/thomas/008": {
									"value": {
										"apiRoute": "/test/thomas/008",
										"methodType": "put",
										"auth": 1,
										"memo": "/test/thomas/008"
									}
								}
							}
						}
					}
				}
			}
		},
		"/qore/auth/{id}": {
			"get": {
				"tags": [
					"qore/auth"
				],
				"summary": "[6046]Qore+API權限_以id查詢(/qore/auth/{id})",
				"parameters": [
					{
						"type": "string",
						"name": "id",
						"in": "query",
						"default": "96",
						"description": "auth_id"
					}
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"code": {
											"type": "integer",
											"description": "",
											"default": 0
										},
										"data": {
											"type": "object",
											"properties": {
												"id": {
													"type": "integer",
													"description": "",
													"default": 96
												},
												"url": {
													"type": "string",
													"description": "",
													"default": "/test/thomas/002"
												},
												"method": {
													"type": "string",
													"description": "",
													"default": "POST"
												},
												"auth": {
													"type": "integer",
													"description": "",
													"default": 1
												},
												"memo": {
													"type": "string",
													"description": "",
													"default": "message"
												},
												"enable": {
													"type": "boolean",
													"description": "",
													"default": true
												},
												"created_at": {
													"type": "string",
													"description": "",
													"default": "2023-02-18T17:35:14.000Z"
												},
												"updated_at": {
													"type": "string",
													"description": "",
													"default": "2023-02-18T17:35:14.000Z"
												}
											},
											"required": [
												
											]
										},
										"msg": {
											"type": "string",
											"description": "",
											"default": "ok"
										}
									},
									"required": [
										
									]
								}
							}
						}
					}
				}
			}
		},
		"/security/pubkey": {
			"get": {
				"tags": [
					"security"
				],
				"summary": "[get]/security/pubkey",
				"parameters": [
					
				],
				"responses": {
					
				}
			}
		},
		"/security/pubkey/encrypt": {
			"post": {
				"tags": [
					"security"
				],
				"summary": "[post]/security/pubkey/encrypt",
				"parameters": [
					
				],
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"code": {
											"type": "integer",
											"description": "",
											"default": 0
										},
										"data": {
											"type": "string",
											"description": "",
											"default": "pv9ffUqyaCglm27WBtR4wh4P1g3hpdoMOx2zVZoa0sPipFpBXOqemyCL7Uk/CiWMPfYfzlJq6CTr2+W9LOxipKn5zaQlkSMv15IJvnsfParwzX0RidE8qPqIOYgz04Yr6Lx+H8LFGUhczMfzKbhUD+sCEK/crtprnMjNmwAgd0Sq1TsSfsSPBENR12kauk6rMjd0IeLPS8tgr6pacyt8vbiLQuahh0/KdFanEZWxmkIoms7Rt7aRHiKm7ncU5pxxed5gXcKief05SSA9ncuwTpzwx+tCu8Tqxn1Zp7tab+3dc/3ckgLu9k4FrlOT7u8uZH6uJg+KzzSYmpmhGJcb4w=="
										},
										"msg": {
											"type": "string",
											"description": "",
											"default": "ok"
										}
									},
									"required": [
										
									]
								}
							}
						}
					}
				},
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"message": {
										"type": "string",
										"description": "",
										"default": "123456"
									}
								},
								"required": [
									"message"
								]
							}
						}
					}
				}
			}
		}
	},
	"components": {
		"securitySchemes": {
			"Token": {
				"type": "apiKey",
				"name": "authorization",
				"in": "header",
				"description": "login取得的token"
			}
		}
	}
}